---
- name: Заблокировать монтирование USB-накопителей
  copy:
    dest: /etc/udev/rules.d/99-block-usb.rules
    content: |
      ACTION=="add", SUBSYSTEM=="block", ENV{ID_BUS}=="usb", RUN+="/bin/sh -c 'echo 1 > /sys\$DEVPATH/../authorized'"
    owner: root
    group: root
    mode: '0644'

- name: Перезагрузить udev
  command: udevadm control --reload-rules

- name: Применить udev
  command: udevadm trigger
